import type { Metadata } from "next";
import "./globals.css";
import Navbar from "../components/navbar/Navbar";
import { VazirFont } from "../utils/fronts";
import Footer from "../components/Footer";

 

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html dir="rtl" lang="fa"  >
      <body className={`p-0 m-0  ${VazirFont.className}`} >
        <Navbar/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
