'use client'
import type { Metadata } from "next";
import "./globals.css";
import Navbar from "../components/navbar/Navbar";
import { VazirFont } from "../utils/fronts";
import Footer from "../components/Footer";
import { AppWrapper } from "../context";

 

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html dir="rtl" lang="fa">
      <body className={` ${VazirFont.className}`}>
        <AppWrapper>
          <Navbar />
          {children}
          <Footer />
        </AppWrapper>
      </body>
    </html>
  );
}
